name: WAE Business CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Write keystore and properties
      - name: Write key
        if: github.event_name != 'pull_request'
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo androidStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
          fi

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Update package name
      - name: Update package name
        run: |
          sed -i 's/applicationId = "com.wmods.wppenhacer"/applicationId = "com.wmods.wppenhacer.w4b"/g' app/build.gradle.kts
          sed -i 's/Wa Enhancer/Wa Enhancer Business/g' app/src/main/res/values/strings.xml
          sed -i 's/com.whatsapp/com.whatsapp.w4b/g' app/src/main/res/values/arrays.xml
          sed -i 's/com.wmods.waenhancer.hookprovider/com.wmods.waenhancer.w4b.hookprovider/g' app/src/main/java/com/wmods/wppenhacer/xposed/bridge/ScopeHook.java
          sed -i 's/com.wmods.waenhancer.hookprovider/com.wmods.waenhancer.w4b.hookprovider/g' app/src/main/AndroidManifest.xml

      # Build and test app
      - name: Build and test app
        run: ./gradlew assembleDebug -Pminify=true

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Wa Enhancer ${{ steps.version.outputs.builddate }}
          path: app/build/outputs/apk/debug/app-debug.apk

      # Upload to release
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/debug/app-debug.apk
          asset_name: WaEnhancer_business_debug_${{ github.sha }}.apk
          tag: pre-release-business-${{ github.sha }}
